### ISSUE TITLE
Duplicate key "Atomic" detected at line 128 (near "    version: "AtomicBrowser"").

### ISSUE THREAD

**Issue by jaydiablo** [endorphin-studio/browser-detector-data#1]
The Symfony YAML parser throws this error when trying to parse with 4.0.2 of https://github.com/endorphin-studio/browser-detector

>Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: Duplicate key "Atomic" detected at line 128 (near "    version: "AtomicBrowser""). in vendor/symfony/yaml/Parser.php:341

I've confirmed that there are two instances of this key in the `browser.yml` file:

https://github.com/endorphin-studio/browser-detector-data/blob/master/var/yaml/browser.yml#L114
and
https://github.com/endorphin-studio/browser-detector-data/blob/master/var/yaml/browser.yml#L127

**Comment by serhiime** [comment]
Thank you for open this issue. it was fixed by contributor and I merged it and make release as 1.0.2 version
