### ISSUE TITLE
Duplicate key

### ISSUE THREAD

**Issue by st7art22** [endorphin-studio/browser-detector-data#2]
https://github.com/endorphin-studio/browser-detector-data/blob/cb1ace9f52f9677616c89f3b80c5148936d47b82/var/yaml/browser.yml#L139

https://github.com/endorphin-studio/browser-detector-data/blob/cb1ace9f52f9677616c89f3b80c5148936d47b82/var/yaml/browser.yml#L137

**Comment by serhiime** [comment]
Thank you for your contribution and fix this issue @st7art22
